### ISSUE TITLE
"error: No calendars."

### ISSUE THREAD

**Issue by Ziut3k77** [cbeardsmore/UpcomingEvents#10] opened 2018-12-17 13:02 UTC
Under macOS Mojave, it appears the icalBuddy command executed by ubersicht doesn't have calendar access permissions, so it returns "error: No calendars." Is it possible to grant those permissions somehow? I have done that for Terminal and iTerm2, and the icalBuddy command works in both terminal applications, but it doesn't work in ubersicht.

**Comment by cbeardsmore** [comment] 2019-02-14 23:29
Closing as duplicate of [#9](https://github.com/cbeardsmore/Upcoming-iCal-Events/issues/9)

**Closed as completed by cbeardsmore** 2019-02-14 23:29 UTC
